<a href="https://colab.research.google.com/github/margret255/Kaggle_Reviews/blob/main/arrays.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns


In [4]:
#1 dimensional array
arr1=np.array([1,2,3,4,5])
print(arr1)




[1 2 3 4 5]


In [6]:
#2 dimensional array
arr2=np.array([[1,2,3],[4,5,6]])
print(arr2)

[[1 2 3]
 [4 5 6]]
